apiVersion: v1
kind: Service
metadata:
  name: stellar-viaduct-frontend
  namespace: stellar-viaduct
  labels:
    app.kubernetes.io/name: stellar-viaduct
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: stellar-viaduct-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
