apiVersion: v1
kind: ServiceAccount
metadata:
  name: stellar-viaduct
  namespace: stellar-viaduct
  labels:
    app.kubernetes.io/name: stellar-viaduct

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stellar-viaduct-role
  namespace: stellar-viaduct
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stellar-viaduct-rolebinding
  namespace: stellar-viaduct
subjects:
  - kind: ServiceAccount
    name: stellar-viaduct
    namespace: stellar-viaduct
roleRef:
  kind: Role
  name: stellar-viaduct-role
  apiGroup: rbac.authorization.k8s.io
